# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.availableBinariesTab = QtWidgets.QWidget()
        self.availableBinariesTab.setObjectName("availableBinariesTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.availableBinariesTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.availableBinariesTable = QtWidgets.QTableWidget(self.availableBinariesTab)
        self.availableBinariesTable.setObjectName("availableBinariesTable")
        self.availableBinariesTable.setColumnCount(6)
        self.availableBinariesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.availableBinariesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.availableBinariesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.availableBinariesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.availableBinariesTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.availableBinariesTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.availableBinariesTable.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.availableBinariesTable)
        self.groupBox = QtWidgets.QGroupBox(self.availableBinariesTab)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.javaVer8CheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.javaVer8CheckBox.setChecked(True)
        self.javaVer8CheckBox.setObjectName("javaVer8CheckBox")
        self.horizontalLayout_2.addWidget(self.javaVer8CheckBox)
        self.javaVer9CheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.javaVer9CheckBox.setObjectName("javaVer9CheckBox")
        self.horizontalLayout_2.addWidget(self.javaVer9CheckBox)
        self.javaVer10CheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.javaVer10CheckBox.setObjectName("javaVer10CheckBox")
        self.horizontalLayout_2.addWidget(self.javaVer10CheckBox)
        self.javaVer11CheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.javaVer11CheckBox.setObjectName("javaVer11CheckBox")
        self.horizontalLayout_2.addWidget(self.javaVer11CheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hotspotVmRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.hotspotVmRadioButton.setObjectName("hotspotVmRadioButton")
        self.vmButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.vmButtonGroup.setObjectName("vmButtonGroup")
        self.vmButtonGroup.addButton(self.hotspotVmRadioButton)
        self.horizontalLayout.addWidget(self.hotspotVmRadioButton)
        self.openj9VmRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.openj9VmRadioButton.setChecked(True)
        self.openj9VmRadioButton.setObjectName("openj9VmRadioButton")
        self.vmButtonGroup.addButton(self.openj9VmRadioButton)
        self.horizontalLayout.addWidget(self.openj9VmRadioButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.formLayout_3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.jreBinRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.jreBinRadioButton.setObjectName("jreBinRadioButton")
        self.binTypeButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.binTypeButtonGroup.setObjectName("binTypeButtonGroup")
        self.binTypeButtonGroup.addButton(self.jreBinRadioButton)
        self.horizontalLayout_3.addWidget(self.jreBinRadioButton)
        self.jdkBinRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.jdkBinRadioButton.setChecked(True)
        self.jdkBinRadioButton.setObjectName("jdkBinRadioButton")
        self.binTypeButtonGroup.addButton(self.jdkBinRadioButton)
        self.horizontalLayout_3.addWidget(self.jdkBinRadioButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.normalHeapSizeRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.normalHeapSizeRadioButton.setChecked(True)
        self.normalHeapSizeRadioButton.setObjectName("normalHeapSizeRadioButton")
        self.heapSizeButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.heapSizeButtonGroup.setObjectName("heapSizeButtonGroup")
        self.heapSizeButtonGroup.addButton(self.normalHeapSizeRadioButton)
        self.horizontalLayout_4.addWidget(self.normalHeapSizeRadioButton)
        self.largeHeapSizeRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.largeHeapSizeRadioButton.setObjectName("largeHeapSizeRadioButton")
        self.heapSizeButtonGroup.addButton(self.largeHeapSizeRadioButton)
        self.horizontalLayout_4.addWidget(self.largeHeapSizeRadioButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.formLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.tabWidget.addTab(self.availableBinariesTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Java Version Manager"))
        item = self.availableBinariesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Release Name"))
        item = self.availableBinariesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "OpenJDK Version"))
        item = self.availableBinariesTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Virtual Machine"))
        item = self.availableBinariesTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Architecture"))
        item = self.availableBinariesTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Binary Type"))
        item = self.availableBinariesTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Binary Size"))
        self.groupBox.setTitle(_translate("MainWindow", "Filter Options"))
        self.label.setText(_translate("MainWindow", "Java Version:"))
        self.javaVer8CheckBox.setText(_translate("MainWindow", "8"))
        self.javaVer9CheckBox.setText(_translate("MainWindow", "9"))
        self.javaVer10CheckBox.setText(_translate("MainWindow", "10"))
        self.javaVer11CheckBox.setText(_translate("MainWindow", "11"))
        self.label_2.setText(_translate("MainWindow", "Virtual Machine:"))
        self.hotspotVmRadioButton.setText(_translate("MainWindow", "HotSpot"))
        self.openj9VmRadioButton.setText(_translate("MainWindow", "OpenJ9"))
        self.label_3.setText(_translate("MainWindow", "Binary Type:"))
        self.jreBinRadioButton.setText(_translate("MainWindow", "JRE"))
        self.jdkBinRadioButton.setText(_translate("MainWindow", "JDK"))
        self.label_4.setText(_translate("MainWindow", "Heap Size:"))
        self.normalHeapSizeRadioButton.setText(_translate("MainWindow", "Normal"))
        self.largeHeapSizeRadioButton.setText(_translate("MainWindow", "Large"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.availableBinariesTab), _translate("MainWindow", "Available Binaries"))

