# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MarkerWindow(object):
    def setupUi(self, MarkerWindow):
        MarkerWindow.setObjectName("MarkerWindow")
        MarkerWindow.resize(918, 446)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        MarkerWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MarkerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.markup_editor = QtWidgets.QPlainTextEdit(self.splitter)
        self.markup_editor.setObjectName("markup_editor")
        self.markup_preview = QtWidgets.QTextBrowser(self.splitter)
        self.markup_preview.setObjectName("markup_preview")
        self.horizontalLayout.addWidget(self.splitter)
        MarkerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MarkerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 21))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_edit = QtWidgets.QMenu(self.menubar)
        self.menu_edit.setObjectName("menu_edit")
        self.menu_selection = QtWidgets.QMenu(self.menubar)
        self.menu_selection.setObjectName("menu_selection")
        self.menu_list = QtWidgets.QMenu(self.menu_selection)
        self.menu_list.setObjectName("menu_list")
        self.menu_Insert_link = QtWidgets.QMenu(self.menu_selection)
        self.menu_Insert_link.setObjectName("menu_Insert_link")
        self.menu_Insert_image = QtWidgets.QMenu(self.menu_selection)
        self.menu_Insert_image.setObjectName("menu_Insert_image")
        self.menu_view = QtWidgets.QMenu(self.menubar)
        self.menu_view.setObjectName("menu_view")
        MarkerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MarkerWindow)
        self.statusbar.setObjectName("statusbar")
        MarkerWindow.setStatusBar(self.statusbar)
        self.action_new_file = QtWidgets.QAction(MarkerWindow)
        self.action_new_file.setObjectName("action_new_file")
        self.action_new_window = QtWidgets.QAction(MarkerWindow)
        self.action_new_window.setObjectName("action_new_window")
        self.action_open_file = QtWidgets.QAction(MarkerWindow)
        self.action_open_file.setObjectName("action_open_file")
        self.action_open_recent = QtWidgets.QAction(MarkerWindow)
        self.action_open_recent.setObjectName("action_open_recent")
        self.action_save = QtWidgets.QAction(MarkerWindow)
        self.action_save.setObjectName("action_save")
        self.action_save_as = QtWidgets.QAction(MarkerWindow)
        self.action_save_as.setObjectName("action_save_as")
        self.action_auto_save = QtWidgets.QAction(MarkerWindow)
        self.action_auto_save.setCheckable(True)
        self.action_auto_save.setObjectName("action_auto_save")
        self.action_undo = QtWidgets.QAction(MarkerWindow)
        self.action_undo.setObjectName("action_undo")
        self.action_redo = QtWidgets.QAction(MarkerWindow)
        self.action_redo.setObjectName("action_redo")
        self.action_cut = QtWidgets.QAction(MarkerWindow)
        self.action_cut.setObjectName("action_cut")
        self.action_copy = QtWidgets.QAction(MarkerWindow)
        self.action_copy.setObjectName("action_copy")
        self.action_paste = QtWidgets.QAction(MarkerWindow)
        self.action_paste.setObjectName("action_paste")
        self.action_find = QtWidgets.QAction(MarkerWindow)
        self.action_find.setObjectName("action_find")
        self.action_replace = QtWidgets.QAction(MarkerWindow)
        self.action_replace.setObjectName("action_replace")
        self.action_select_all = QtWidgets.QAction(MarkerWindow)
        self.action_select_all.setObjectName("action_select_all")
        self.action_word_wrap = QtWidgets.QAction(MarkerWindow)
        self.action_word_wrap.setCheckable(True)
        self.action_word_wrap.setObjectName("action_word_wrap")
        self.action_increase_zoom = QtWidgets.QAction(MarkerWindow)
        self.action_increase_zoom.setObjectName("action_increase_zoom")
        self.action_decrease_zoom = QtWidgets.QAction(MarkerWindow)
        self.action_decrease_zoom.setObjectName("action_decrease_zoom")
        self.action_reset_zoom = QtWidgets.QAction(MarkerWindow)
        self.action_reset_zoom.setObjectName("action_reset_zoom")
        self.action_expand_editor = QtWidgets.QAction(MarkerWindow)
        self.action_expand_editor.setObjectName("action_expand_editor")
        self.action_expand_preview = QtWidgets.QAction(MarkerWindow)
        self.action_expand_preview.setObjectName("action_expand_preview")
        self.action_preferences = QtWidgets.QAction(MarkerWindow)
        self.action_preferences.setObjectName("action_preferences")
        self.action_increase_indent = QtWidgets.QAction(MarkerWindow)
        self.action_increase_indent.setObjectName("action_increase_indent")
        self.action_decrease_indent = QtWidgets.QAction(MarkerWindow)
        self.action_decrease_indent.setObjectName("action_decrease_indent")
        self.action_close = QtWidgets.QAction(MarkerWindow)
        self.action_close.setObjectName("action_close")
        self.action_bold = QtWidgets.QAction(MarkerWindow)
        self.action_bold.setObjectName("action_bold")
        self.action_italic = QtWidgets.QAction(MarkerWindow)
        self.action_italic.setObjectName("action_italic")
        self.action_underline = QtWidgets.QAction(MarkerWindow)
        self.action_underline.setObjectName("action_underline")
        self.action_strikethrough = QtWidgets.QAction(MarkerWindow)
        self.action_strikethrough.setObjectName("action_strikethrough")
        self.action_superscript = QtWidgets.QAction(MarkerWindow)
        self.action_superscript.setObjectName("action_superscript")
        self.action_subscript = QtWidgets.QAction(MarkerWindow)
        self.action_subscript.setObjectName("action_subscript")
        self.action_ordered_list = QtWidgets.QAction(MarkerWindow)
        self.action_ordered_list.setObjectName("action_ordered_list")
        self.action_unordered_list = QtWidgets.QAction(MarkerWindow)
        self.action_unordered_list.setObjectName("action_unordered_list")
        self.action_insert_link_inline = QtWidgets.QAction(MarkerWindow)
        self.action_insert_link_inline.setObjectName(
            "action_insert_link_inline")
        self.action_insert_link_reference = QtWidgets.QAction(MarkerWindow)
        self.action_insert_link_reference.setObjectName(
            "action_insert_link_reference")
        self.action_insert_image_inline = QtWidgets.QAction(MarkerWindow)
        self.action_insert_image_inline.setObjectName(
            "action_insert_image_inline")
        self.action_insert_image_reference = QtWidgets.QAction(MarkerWindow)
        self.action_insert_image_reference.setObjectName(
            "action_insert_image_reference")
        self.menu_file.addAction(self.action_new_file)
        self.menu_file.addAction(self.action_new_window)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_open_file)
        self.menu_file.addAction(self.action_open_recent)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_save)
        self.menu_file.addAction(self.action_save_as)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_auto_save)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_preferences)
        self.menu_file.addAction(self.action_close)
        self.menu_edit.addAction(self.action_undo)
        self.menu_edit.addAction(self.action_redo)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.action_cut)
        self.menu_edit.addAction(self.action_copy)
        self.menu_edit.addAction(self.action_paste)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.action_find)
        self.menu_edit.addAction(self.action_replace)
        self.menu_list.addAction(self.action_ordered_list)
        self.menu_list.addAction(self.action_unordered_list)
        self.menu_Insert_link.addAction(self.action_insert_link_inline)
        self.menu_Insert_link.addAction(self.action_insert_link_reference)
        self.menu_Insert_image.addAction(self.action_insert_image_inline)
        self.menu_Insert_image.addAction(self.action_insert_image_reference)
        self.menu_selection.addAction(self.action_select_all)
        self.menu_selection.addSeparator()
        self.menu_selection.addAction(self.action_increase_indent)
        self.menu_selection.addAction(self.action_decrease_indent)
        self.menu_selection.addSeparator()
        self.menu_selection.addAction(self.action_bold)
        self.menu_selection.addAction(self.action_italic)
        self.menu_selection.addAction(self.action_underline)
        self.menu_selection.addAction(self.action_strikethrough)
        self.menu_selection.addSeparator()
        self.menu_selection.addAction(self.action_superscript)
        self.menu_selection.addAction(self.action_subscript)
        self.menu_selection.addSeparator()
        self.menu_selection.addAction(self.menu_Insert_link.menuAction())
        self.menu_selection.addAction(self.menu_Insert_image.menuAction())
        self.menu_selection.addSeparator()
        self.menu_selection.addAction(self.menu_list.menuAction())
        self.menu_view.addAction(self.action_word_wrap)
        self.menu_view.addSeparator()
        self.menu_view.addAction(self.action_increase_zoom)
        self.menu_view.addAction(self.action_decrease_zoom)
        self.menu_view.addAction(self.action_reset_zoom)
        self.menu_view.addSeparator()
        self.menu_view.addAction(self.action_expand_editor)
        self.menu_view.addAction(self.action_expand_preview)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menu_selection.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())

        self.retranslateUi(MarkerWindow)
        QtCore.QMetaObject.connectSlotsByName(MarkerWindow)

    def retranslateUi(self, MarkerWindow):
        _translate = QtCore.QCoreApplication.translate
        MarkerWindow.setWindowTitle(_translate("MarkerWindow", "MainWindow"))
        self.menu_file.setTitle(_translate("MarkerWindow", "File"))
        self.menu_edit.setTitle(_translate("MarkerWindow", "Edit"))
        self.menu_selection.setTitle(_translate("MarkerWindow", "Selection"))
        self.menu_list.setTitle(_translate("MarkerWindow", "Format List"))
        self.menu_Insert_link.setTitle(
            _translate("MarkerWindow", "Insert Link"))
        self.menu_Insert_image.setTitle(
            _translate("MarkerWindow", "Insert Image"))
        self.menu_view.setTitle(_translate("MarkerWindow", "View"))
        self.action_new_file.setText(_translate("MarkerWindow", "New File..."))
        self.action_new_file.setShortcut(_translate("MarkerWindow", "Ctrl+N"))
        self.action_new_window.setText(
            _translate("MarkerWindow", "New Window"))
        self.action_new_window.setShortcut(
            _translate("MarkerWindow", "Ctrl+W"))
        self.action_open_file.setText(
            _translate("MarkerWindow", "Open File..."))
        self.action_open_file.setShortcut(_translate("MarkerWindow", "Ctrl+O"))
        self.action_open_recent.setText(
            _translate("MarkerWindow", "Open Recent"))
        self.action_save.setText(_translate("MarkerWindow", "Save"))
        self.action_save.setShortcut(_translate("MarkerWindow", "Ctrl+S"))
        self.action_save_as.setText(_translate("MarkerWindow", "Save As..."))
        self.action_save_as.setShortcut(
            _translate("MarkerWindow", "Ctrl+Shift+S"))
        self.action_auto_save.setText(_translate("MarkerWindow", "Auto Save"))
        self.action_undo.setText(_translate("MarkerWindow", "Undo"))
        self.action_undo.setShortcut(_translate("MarkerWindow", "Ctrl+Z"))
        self.action_redo.setText(_translate("MarkerWindow", "Redo"))
        self.action_redo.setShortcut(_translate("MarkerWindow", "Ctrl+Y"))
        self.action_cut.setText(_translate("MarkerWindow", "Cut"))
        self.action_cut.setShortcut(_translate("MarkerWindow", "Ctrl+X"))
        self.action_copy.setText(_translate("MarkerWindow", "Copy"))
        self.action_copy.setShortcut(_translate("MarkerWindow", "Ctrl+C"))
        self.action_paste.setText(_translate("MarkerWindow", "Paste"))
        self.action_paste.setShortcut(_translate("MarkerWindow", "Ctrl+V"))
        self.action_find.setText(_translate("MarkerWindow", "Find"))
        self.action_find.setShortcut(_translate("MarkerWindow", "Ctrl+F"))
        self.action_replace.setText(_translate("MarkerWindow", "Replace"))
        self.action_replace.setShortcut(_translate("MarkerWindow", "Ctrl+R"))
        self.action_select_all.setText(
            _translate("MarkerWindow", "Select All"))
        self.action_select_all.setShortcut(
            _translate("MarkerWindow", "Ctrl+A"))
        self.action_word_wrap.setText(_translate("MarkerWindow", "Word Wrap"))
        self.action_increase_zoom.setText(
            _translate("MarkerWindow", "Zoom In"))
        self.action_increase_zoom.setShortcut(
            _translate("MarkerWindow", "Ctrl+="))
        self.action_decrease_zoom.setText(
            _translate("MarkerWindow", "Zoom Out"))
        self.action_decrease_zoom.setShortcut(
            _translate("MarkerWindow", "Ctrl+-"))
        self.action_reset_zoom.setText(
            _translate("MarkerWindow", "Reset Zoom"))
        self.action_reset_zoom.setShortcut(
            _translate("MarkerWindow", "Ctrl+0"))
        self.action_expand_editor.setText(
            _translate("MarkerWindow", "Expand Editor"))
        self.action_expand_preview.setText(
            _translate("MarkerWindow", "Expand Preview"))
        self.action_preferences.setText(
            _translate("MarkerWindow", "Preferences"))
        self.action_preferences.setShortcut(
            _translate("MarkerWindow", "Ctrl+Shift+."))
        self.action_increase_indent.setText(
            _translate("MarkerWindow", "Increase Indent"))
        self.action_increase_indent.setShortcut(
            _translate("MarkerWindow", "Alt+Shift+Right"))
        self.action_decrease_indent.setText(
            _translate("MarkerWindow", "Decrease Indent"))
        self.action_decrease_indent.setShortcut(
            _translate("MarkerWindow", "Alt+Shift+Left"))
        self.action_close.setText(_translate("MarkerWindow", "Close"))
        self.action_close.setShortcut(
            _translate("MarkerWindow", "Ctrl+Shift+Q"))
        self.action_bold.setText(_translate("MarkerWindow", "Bold"))
        self.action_bold.setShortcut(_translate("MarkerWindow", "Ctrl+B"))
        self.action_italic.setText(_translate("MarkerWindow", "Italic"))
        self.action_italic.setShortcut(_translate("MarkerWindow", "Ctrl+I"))
        self.action_underline.setText(_translate("MarkerWindow", "Underline"))
        self.action_underline.setShortcut(_translate("MarkerWindow", "Ctrl+U"))
        self.action_strikethrough.setText(
            _translate("MarkerWindow", "Strikethrough"))
        self.action_strikethrough.setShortcut(
            _translate("MarkerWindow", "Alt+Shift+5"))
        self.action_superscript.setText(
            _translate("MarkerWindow", "Superscript"))
        self.action_superscript.setShortcut(
            _translate("MarkerWindow", "Ctrl+."))
        self.action_subscript.setText(_translate("MarkerWindow", "Subscript"))
        self.action_subscript.setShortcut(_translate("MarkerWindow", "Ctrl+,"))
        self.action_ordered_list.setText(_translate("MarkerWindow", "Ordered"))
        self.action_unordered_list.setText(
            _translate("MarkerWindow", "Unordered"))
        self.action_insert_link_inline.setText(
            _translate("MarkerWindow", "Inline"))
        self.action_insert_link_inline.setShortcut(
            _translate("MarkerWindow", "Ctrl+K"))
        self.action_insert_link_reference.setText(
            _translate("MarkerWindow", "Reference"))
        self.action_insert_image_inline.setText(
            _translate("MarkerWindow", "Inline"))
        self.action_insert_image_reference.setText(
            _translate("MarkerWindow", "Reference"))
